### ISSUE TITLE
Problems with make gou version

### ISSUE THREAD

**Issue by thomaram** [OPM/LBPM#2]
I get the following error when building on GPU: 

"common/ArraySize.h:291:1: error: expression ‘<throw-expression>’ is not a constant-expression"

**Comment by thomaram** [comment]
The error still persists even when I set to c++14. However, with explicit c++11 I get more errors/warnings.

**Comment by JamesEMcClure** [comment]
What compiler version are you using?

**Comment by thomaram** [comment]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by JamesEMcClure** [comment]
I will take a look.
