### ISSUE TITLE
Build errors: A lot undefined identifiers "DB*"

### ISSUE THREAD

**Issue by JingR2020** [OPM/LBPM#36]
Hi, 

My build generated a lot of similar undefined identifier such as "DB_DOUBLE", "DB_INT", "DB_FLOAT", "DBGetUcdmesh", "DBGetUcdvar", "DBGetPointvar", etc. I checked all of source code without finding definitions of these types. Do I missing something?

I am using master branch commit 4b92170d

Thanks

**Comment by JamesEMcClure** [comment]
I think these are defined in the Silo library, which LBPM uses to support I/O.  Make sure that the path to the silo library is listed in the LD_LIBRARY_PATH setting.

**Comment by JingR2020** [comment]
> I think these are defined in the Silo library, which LBPM uses to support I/O. Make sure that the path to the silo library is listed in the LD_LIBRARY_PATH setting.

I have SILO_DIRECTORY and SILO_LIB defined in cmake environment, then I also added silo lib path to LD_LIBRARY_PATH, I still got the same errors.

**Comment by JamesEMcClure** [comment]
Try setting the following in the CMake configure script:

`    -D USE_HDF5=1                        \
        -D HDF5_DIRECTORY="$HDF5_DIR"		   \
    	-D HDF5_LIB="$HDF5_DIR/lib/libhdf5.a"	   \
     -D USE_SILO=1                        \
        -D SILO_LIB="$SILO_DIR/lib/libsiloh5.a"    \
   	-D SILO_DIRECTORY="$SILO_DIR"		     \`

**Comment by JingR2020** [comment]
> Try setting the following in the CMake configure script:
> 
> ```
>         -D HDF5_DIRECTORY="$HDF5_DIR"		   \
>     	-D HDF5_LIB="$HDF5_DIR/lib/libhdf5.a"	   \
>      -D USE_SILO=1                        \
>         -D SILO_LIB="$SILO_DIR/lib/libsiloh5.a"    \
>    	-D SILO_DIRECTORY="$SILO_DIR"		     \
> ```

Thanks for your help. But I have all these variables defined in CMake configuration script. Are you sure all those DB* symbols are defined in Silo? I checked objects in all the source files of Silo and library libsilo.a that was built from source, but I couldn't find any DB* symbol. My silo source is master branch commit #f3ac9f32.

**Comment by JamesEMcClure** [comment]
I am pretty sure. You can check search the library for the missing routines, i.e. use the `nm` command and use `grep` to fileter the output,
```
 nm /opt/apps/silo/lib/libsiloh5.a | grep DBGetUcd
```
On my machine I will see both of these libraries.
```
000000000001ebac T DBGetUcdmesh
000000000001f691 T DBGetUcdvar
```
I think that you won't see `DB_DOUBLE` , `DB_INT` `DB_FLOAT` because these are the silo data types, which are not library routines. 

 Note you may have installed silo to a different path compared to where I installed it,  so just make sure you change the path to match where you installed it to.

**Comment by JingR2020** [comment]
@JamesEMcClure , Appreciate all your help!

I have found the real issue now. I built wrong Silo (https://github.com/stanford-mast/Silo). I guess "Silo" name is so popular that it is really hard to find the right one with google search.

Suggestion to the maintainers of this project: It would be better if you can provide more specific keyword about Silo or project link, since it is such an important dependent package to this project.
