### ISSUE TITLE
LBPM color simulator - aborting problem

### ISSUE THREAD

**Issue by to3sk** [OPM/LBPM#37]
Hi LBPM community,

I have a problem with running the LBPM color simulator, I installed LBPM and all the tests were completed successfully. However, when I try to run examples manually (e.g. Piston) I receive following:
Program abort called in file '/home/tom/lbo/lbpm/LBPM/common/Database.cpp' at line 83: Variable FlowAdaptor was not found in database 

I also tried to run several other examples and it returns the same error. I would appreciate the advice on how to solve this issue.

**Comment by JamesEMcClure** [comment]
You can solve this by adding the following lines to your input file.  I will update the example scripts so that they include this.

```
FlowAdaptor {

}
```
