### ISSUE TITLE
Shell aggregation protocol- sudden jump in water saturation

### ISSUE THREAD

**Issue by maldiH** [OPM/LBPM#42]
Hi LBPM Community,

I am facing with some issues- a considerable increase in water saturation (from 0.19 to almost 0.526 without reaching steady state). My understanding is that at shell aggregation protocol, the saturation should slowly increase (to avoid instability) and stay constant until steady state is reached. I am attaching the timely.csv and input file. I am not sure if morph_delta is correctly set and the parameters seem to be in a stable range. If you could give some advice on that, that would be greatly appreciated! Thanks a lot!

Domain {
    Filename = "mask_water_flooded_water_and_oil.raw.morphdrain.raw"
    ReadType = "8bit"
    N = 400, 400, 400
    nproc = 2, 2, 2     // Number of processors (Npx,Npy,Npz)
    n = 200, 200, 200   // Size of local domain (Nx,Ny,Nz)
    voxel_length = 7.0       // voxel_length (in microns)
    ReadValues = 0, 1, 2   //labels within the original image
    WriteValues = 0, 1, 2         // Length of domain (x,y,z
    BC = 0              // Boundary condition type
    InletLayers = 0, 0, 10
    checkerSize = 10
    Sw = 0.15
}

MRT {
    timestepMax = 100000
    tau = 0.7
    F = 0, 0, 1.0e-5
    Restart = false
    tolerance = 0.000005
    din = 1.0
    dout = 1.0
}
Color {
    tauA = 0.7  //nw
    tauB = 0.7  //w
    rhoA = 0.1
    rhoB = 0.1
    alpha = 5.0e-3
    beta = 0.95
    F = 0, 0, 2.0e-5
    Restart = false
    timestepMax = 1500000
    ComponentLabels = 0
    ComponentAffinity = -0.8
    interval = 50000
    tol = 0.005
    rescale_force_after_timestep = 100000
    capillary_number = 1.0e-5
    protocol = "shell aggregation"
    
}

Analysis {
    min_steady_timesteps = 50000
    max_steady_timesteps = 100000 
    morph_delta = -0.08
    tolerance = 0.005
    morph_interval = 10000
    analysis_interval = 1000
    visualization_interval = 100000
    restart_interval = 100000
    restart_file = "Restart"
    N_threads = 4
    load_balance = "independent"
}

Visualization {
}

timely.csv:

0,09652912 | 0,33914703 | 12,645002 | 7,27E-06 | 0,00027096 | 1,00E-05 | 0,325385
-- | -- | -- | -- | -- | -- | --
0,09749646 | -0,182741 | 9,2212694 | -3,92E-06 | 0,0001976 | 1,00E-05 | 0,3241489
0,0982583 | -0,1567175 | 7,9492281 | -3,36E-06 | 0,00017034 | 1,00E-05 | 0,32343268
0,09882185 | -0,1185749 | 7,6547856 | -2,54E-06 | 0,00016403 | 1,00E-05 | 0,32293858
0,09930045 | -0,177368 | 7,5156894 | -3,80E-06 | 0,00016105 | 1,00E-05 | 0,32258447
0,09976532 | -0,2726988 | 7,4951811 | -5,84E-06 | 0,00016061 | 1,00E-05 | 0,32229226
0,10019139 | -0,3006274 | 7,3374356 | -6,44E-06 | 0,00015723 | 1,00E-05 | 0,32203757
0,10053486 | -0,3069982 | 7,0985911 | -6,58E-06 | 0,00015211 | 1,00E-05 | 0,32183572
0,10085145 | -0,3049429 | 6,9313614 | -6,53E-06 | 0,00014853 | 1,00E-05 | 0,32166542
0,10102838 | -0,2470993 | 7,046487 | -5,29E-06 | 0,000151 | 1,00E-05 | 0,32156006
0,10123714 | -0,2905315 | 7,0261647 | -6,23E-06 | 0,00015056 | 1,00E-05 | 0,32148013
0,10143996 | -0,3640848 | 6,9817254 | -7,80E-06 | 0,00014961 | 1,00E-05 | 0,32144767
0,1016473 | -0,3903071 | 6,8574137 | -8,36E-06 | 0,00014694 | 1,00E-05 | 0,32142416
0,1019225 | -0,3803113 | 6,9027813 | -8,15E-06 | 0,00014792 | 1,00E-05 | 0,32135969
0,19656327 | 0,21649752 | 9,3996573 | 9,28E-06 | 0,00040284 | 2,00E-05 | 0,32673009
0,19741559 | 0,12988241 | 7,0004523 | 5,57E-06 | 0,00030002 | 2,00E-05 | 0,32570895
0,19779525 | 0,01670027 | 6,3253411 | 7,16E-07 | 0,00027109 | 2,00E-05 | 0,32516147
0,19798316 | -0,0924314 | 5,9242257 | -3,96E-06 | 0,0002539 | 2,00E-05 | 0,32479344
0,19810898 | -0,126722 | 5,6920835 | -5,43E-06 | 0,00024395 | 2,00E-05 | 0,32451396
0,19824185 | -0,1558488 | 5,5472852 | -6,68E-06 | 0,00023774 | 2,00E-05 | 0,32429334
0,19838401 | -0,1706258 | 5,4217139 | -7,31E-06 | 0,00023236 | 2,00E-05 | 0,32411519
0,19846779 | -0,1767335 | 5,3422843 | -7,57E-06 | 0,00022896 | 2,00E-05 | 0,3239634
0,19856002 | -0,2167776 | 5,3746989 | -9,29E-06 | 0,00023034 | 2,00E-05 | 0,32383152
0,19861707 | -0,2371914 | 5,3645912 | -1,02E-05 | 0,00022991 | 2,00E-05 | 0,3237249
0,19871635 | -0,243085 | 5,2812737 | -1,04E-05 | 0,00022634 | 2,00E-05 | 0,32362987
0,19877691 | -0,2561522 | 5,1681489 | -1,10E-05 | 0,00022149 | 2,00E-05 | 0,3235513
0,19890501 | -0,2646984 | 5,1809218 | -1,13E-05 | 0,00022204 | 2,00E-05 | 0,32347399
0,19906778 | -0,2744509 | 5,1819205 | -1,18E-05 | 0,00022208 | 2,00E-05 | 0,32339448
0,199205 | -0,2684831 | 5,1482323 | -1,15E-05 | 0,00022064 | 2,00E-05 | 0,32332391
0,19923055 | -0,261193 | 5,0845829 | -1,12E-05 | 0,00021791 | 2,00E-05 | 0,32328235
0,19923993 | -0,2894458 | 5,0732123 | -1,24E-05 | 0,00021742 | 2,00E-05 | 0,32324076
0,19927679 | -0,2795184 | 5,0876385 | -1,20E-05 | 0,00021804 | 2,00E-05 | 0,32320201
0,19939157 | -0,2771437 | 5,0478683 | -1,19E-05 | 0,00021634 | 2,00E-05 | 0,32314474
0,1994451 | -0,3118966 | 5,1518537 | -1,34E-05 | 0,00022079 | 2,00E-05 | 0,32310275
0,19945909 | -0,2965397 | 5,1493105 | -1,27E-05 | 0,00022068 | 2,00E-05 | 0,32306689
0,19948011 | -0,321405 | 5,185006 | -1,38E-05 | 0,00022221 | 2,00E-05 | 0,32303481
0,19950525 | -0,315716 | 5,2943462 | -1,35E-05 | 0,0002269 | 2,00E-05 | 0,32300702
0,19954655 | -0,3293322 | 5,3174167 | -1,41E-05 | 0,00022789 | 2,00E-05 | 0,32297936
0,19960025 | -0,3335532 | 5,3354293 | -1,43E-05 | 0,00022866 | 2,00E-05 | 0,32294988
0,19968008 | -0,3416391 | 5,3486513 | -1,46E-05 | 0,00022923 | 2,00E-05 | 0,32291655
0,19966517 | -0,3416142 | 5,3754666 | -1,46E-05 | 0,00023038 | 2,00E-05 | 0,32289064
0,19967221 | -0,3485097 | 5,3825893 | -1,49E-05 | 0,00023068 | 2,00E-05 | 0,32286678
0,19965529 | -0,3447644 | 5,3215647 | -1,48E-05 | 0,00022807 | 2,00E-05 | 0,32285089
0,19962588 | -0,3502551 | 5,2329095 | -1,50E-05 | 0,00022427 | 2,00E-05 | 0,32283689
0,19961156 | -0,3564831 | 5,2701663 | -1,53E-05 | 0,00022586 | 2,00E-05 | 0,32281526
0,19963342 | -0,3343766 | 5,2713637 | -1,43E-05 | 0,00022592 | 2,00E-05 | 0,32279015
0,19968729 | -0,3415055 | 5,2353727 | -1,46E-05 | 0,00022437 | 2,00E-05 | 0,32276531
0,19973454 | -0,3455842 | 5,232203 | -1,48E-05 | 0,00022424 | 2,00E-05 | 0,32274296
0,19975741 | -0,3347595 | 5,2230905 | -1,43E-05 | 0,00022385 | 2,00E-05 | 0,32272579
0,19975716 | -0,3284145 | 5,2372202 | -1,41E-05 | 0,00022445 | 2,00E-05 | 0,3227124
0,19974601 | -0,3074401 | 5,1880189 | -1,32E-05 | 0,00022234 | 2,00E-05 | 0,32270789
0,19970857 | -0,3075214 | 5,1893273 | -1,32E-05 | 0,0002224 | 2,00E-05 | 0,32270763
0,19972298 | -0,3110589 | 5,2436675 | -1,33E-05 | 0,00022473 | 2,00E-05 | 0,3226978
0,19973646 | -0,3216303 | 5,2372058 | -1,38E-05 | 0,00022445 | 2,00E-05 | 0,32268487
0,1997089 | -0,3098836 | 5,289485 | -1,33E-05 | 0,00022669 | 2,00E-05 | 0,32267975
0,19970069 | -0,3210831 | 5,2412771 | -1,38E-05 | 0,00022463 | 2,00E-05 | 0,32267463
0,19972247 | -0,3509908 | 5,2017581 | -1,50E-05 | 0,00022293 | 2,00E-05 | 0,32267659
0,19969206 | -0,3292709 | 5,196579 | -1,41E-05 | 0,00022271 | 2,00E-05 | 0,32268883
0,19970178 | -0,3187651 | 5,2236938 | -1,37E-05 | 0,00022387 | 2,00E-05 | 0,32268773
0,1997311 | -0,308336 | 5,2491935 | -1,32E-05 | 0,00022497 | 2,00E-05 | 0,322684
0,19979209 | -0,2972883 | 5,2284751 | -1,27E-05 | 0,00022408 | 2,00E-05 | 0,32267636
0,19979737 | -0,3011131 | 5,2102983 | -1,29E-05 | 0,0002233 | 2,00E-05 | 0,32267341
0,1998344 | -0,2887127 | 5,2126077 | -1,24E-05 | 0,0002234 | 2,00E-05 | 0,32266814
0,1998757 | -0,2850104 | 5,2415404 | -1,22E-05 | 0,00022464 | 2,00E-05 | 0,32265729
0,19991591 | -0,2824011 | 5,2540569 | -1,21E-05 | 0,00022517 | 2,00E-05 | 0,32264934
0,19994883 | -0,2776725 | 5,2281364 | -1,19E-05 | 0,00022406 | 2,00E-05 | 0,32264213
0,19997145 | -0,2773151 | 5,2021018 | -1,19E-05 | 0,00022295 | 2,00E-05 | 0,32263461
0,19998209 | -0,2861474 | 5,1860247 | -1,23E-05 | 0,00022226 | 2,00E-05 | 0,3226307
0,19994012 | -0,2571384 | 5,1407063 | -1,10E-05 | 0,00022032 | 2,00E-05 | 0,32264371
0,19984914 | -0,2292873 | 5,0512771 | -9,83E-06 | 0,00021648 | 2,00E-05 | 0,32266985
0,19982736 | -0,2446022 | 5,1128388 | -1,05E-05 | 0,00021912 | 2,00E-05 | 0,32267954
0,1997838 | -0,2645397 | 5,132461 | -1,13E-05 | 0,00021996 | 2,00E-05 | 0,32268468
0,19975339 | -0,2447243 | 5,1469347 | -1,05E-05 | 0,00022058 | 2,00E-05 | 0,32268752
0,19975841 | -0,2515587 | 5,1186218 | -1,08E-05 | 0,00021937 | 2,00E-05 | 0,32268314
0,19975732 | -0,2443865 | 5,0853068 | -1,05E-05 | 0,00021794 | 2,00E-05 | 0,32268415
0,19972415 | -0,2528157 | 5,1225521 | -1,08E-05 | 0,00021954 | 2,00E-05 | 0,32269478
0,19967749 | -0,2634156 | 5,1593956 | -1,13E-05 | 0,00022112 | 2,00E-05 | 0,32271079
0,19966869 | -0,2576288 | 5,1221561 | -1,10E-05 | 0,00021952 | 2,00E-05 | 0,32272234
0,19964632 | -0,2305535 | 5,0801052 | -9,88E-06 | 0,00021772 | 2,00E-05 | 0,32273034
0,1996397 | -0,2582941 | 5,1121944 | -1,11E-05 | 0,00021909 | 2,00E-05 | 0,32273289
0,19967531 | -0,2462708 | 5,0434214 | -1,06E-05 | 0,00021615 | 2,00E-05 | 0,32272949
0,19968159 | -0,247921 | 5,0407792 | -1,06E-05 | 0,00021603 | 2,00E-05 | 0,32272875
0,19968561 | -0,2423178 | 5,022662 | -1,04E-05 | 0,00021526 | 2,00E-05 | 0,32272723
0,19972348 | -0,2459865 | 5,0036179 | -1,05E-05 | 0,00021444 | 2,00E-05 | 0,32272336
0,19974526 | -0,2455137 | 5,016462 | -1,05E-05 | 0,00021499 | 2,00E-05 | 0,32272113
0,19975179 | -0,2446156 | 4,9887038 | -1,05E-05 | 0,0002138 | 2,00E-05 | 0,32272267
0,19978212 | -0,2314215 | 4,9470573 | -9,92E-06 | 0,00021202 | 2,00E-05 | 0,32271923
0,19981094 | -0,2406805 | 5,016004 | -1,03E-05 | 0,00021497 | 2,00E-05 | 0,32271848
0,19980466 | -0,2159591 | 5,0713607 | -9,26E-06 | 0,00021734 | 2,00E-05 | 0,3227246
0,19978019 | -0,1892791 | 5,0886949 | -8,11E-06 | 0,00021809 | 2,00E-05 | 0,32273382
0,19979276 | -0,2246794 | 5,0370121 | -9,63E-06 | 0,00021587 | 2,00E-05 | 0,32274171
0,19982233 | -0,215759 | 5,0109534 | -9,25E-06 | 0,00021476 | 2,00E-05 | 0,32274248
0,26302888 | -0,2071337 | 5,575635 | -1,31E-05 | 0,00035381 | 2,96E-05 | 0,32218178
0,30781828 | -0,1040591 | 3,7511474 | -6,60E-06 | 0,00023804 | 2,96E-05 | 0,32300473
0,34439791 | -0,0555103 | 2,8122134 | -3,52E-06 | 0,00017846 | 2,96E-05 | 0,32385841
0,37639333 | -0,0167514 | 1,7905573 | -1,06E-06 | 0,00011362 | 2,96E-05 | 0,32461015
0,40471425 | 0,14972249 | 1,4961106 | 9,50E-06 | 9,49E-05 | 2,96E-05 | 0,32527576
0,43030825 | 0,31010079 | 1,1430151 | 1,97E-05 | 7,25E-05 | 2,96E-05 | 0,32584309
0,45325673 | 0,49221009 | 0,88969844 | 3,12E-05 | 5,65E-05 | 2,96E-05 | 0,32634791
0,47415854 | 0,57527463 | 0,41650762 | 3,65E-05 | 2,64E-05 | 2,96E-05 | 0,32678955
0,4933 | 0,8665231 | 0,42563855 | 5,50E-05 | 2,70E-05 | 2,96E-05 | 0,32717819
0,51119775 | 1,0080872 | 0,18862398 | 6,40E-05 | 1,20E-05 | 2,96E-05 | 0,32750112
0,52435824 | 1,2417336 | 0,33560762 | 7,88E-05 | 2,13E-05 | 2,96E-05 | 0,32773602
0,52495346 | 1,1552595 | -0,3950354 | 7,33E-05 | -2,51E-05 | 2,96E-05 | 0,32775717
0,52523628 | 1,0161233 | -0,6819782 | 6,45E-05 | -4,33E-05 | 2,96E-05 | 0,32776953
0,5254587 | 1,0652276 | -0,4441319 | 6,76E-05 | -2,82E-05 | 2,96E-05 | 0,32777238
0,52566713 | 1,0272137 | -0,5814978 | 6,52E-05 | -3,69E-05 | 2,96E-05 | 0,32777352
0,52581197 | 1,008539 | -0,5075675 | 6,40E-05 | -3,22E-05 | 2,96E-05 | 0,32777218
0,52584104 | 0,96737909 | -0,6121425 | 6,14E-05 | -3,88E-05 | 2,96E-05 | 0,32777936
0,52589918 | 0,97791978 | -0,67741 | 6,21E-05 | -4,30E-05 | 2,96E-05 | 0,32778507
0,52594609 | 0,96510854 | -0,6896958 | 6,12E-05 | -4,38E-05 | 2,96E-05 | 0,3277881
0,52598363 | 0,93466951 | -0,7682801 | 5,93E-05 | -4,88E-05 | 2,96E-05 | 0,32779221
0,52598798 | 0,91812708 | -0,7992486 | 5,83E-05 | -5,07E-05 | 2,96E-05 | 0,32779725
0,52598245 | 0,91549786 | -0,8201398 | 5,81E-05 | -5,20E-05 | 2,96E-05 | 0,32779896
0,52605307 | 0,96428868 | -0,6878149 | 6,12E-05 | -4,36E-05 | 2,96E-05 | 0,3277979
0,52610116 | 0,91431536 | -0,8565948 | 5,80E-05 | -5,44E-05 | 2,96E-05 | 0,3278
0,52611724 | 0,89264886 | -0,9005677 | 5,66E-05 | -5,71E-05 | 2,96E-05 | 0,3278027
0,52615955 | 0,87668007 | -0,9296484 | 5,56E-05 | -5,90E-05 | 2,96E-05 | 0,32780334
0,52627625 | 0,88206413 | -0,923966 | 5,60E-05 | -5,86E-05 | 2,96E-05 | 0,32779727
0,52630565 | 0,90863331 | -0,9048941 | 5,77E-05 | -5,74E-05 | 2,96E-05 | 0,3277973
0,52632207 | 0,87530098 | -0,9187583 | 5,55E-05 | -5,83E-05 | 2,96E-05 | 0,32779699
0,52633204 | 0,88886043 | -0,9310545 | 5,64E-05 | -5,91E-05 | 2,96E-05 | 0,32779694
0,52638591 | 0,8835896 | -0,8889361 | 5,61E-05 | -5,64E-05 | 2,96E-05 | 0,32779359
0,52640141 | 0,86380515 | -0,9099203 | 5,48E-05 | -5,77E-05 | 2,96E-05 | 0,32779395
0,52646616 | 0,92835169 | -0,9093145 | 5,89E-05 | -5,77E-05 | 2,96E-05 | 0,32779177
0,52650101 | 0,89313631 | -0,9442459 | 5,67E-05 | -5,99E-05 | 2,96E-05 | 0,32779057
0,52656854 | 0,88499445 | -0,9340142 | 5,62E-05 | -5,93E-05 | 2,96E-05 | 0,3277886
0,52657758 | 0,86031515 | -0,9708825 | 5,46E-05 | -6,16E-05 | 2,96E-05 | 0,32778806
0,52657658 | 0,84064456 | -1,0286085 | 5,33E-05 | -6,53E-05 | 2,96E-05 | 0,32779031
0,52659895 | 0,85225837 | -1,0369301 | 5,41E-05 | -6,58E-05 | 2,96E-05 | 0,32779205

**Comment by JamesEMcClure** [comment]
One thing you might check is the image resolution, which can be assessed using a morphological approach

https://github.com/OPM/LBPM/wiki/LBPM-Tutorial,-Step-7.--Morphological--Initial-Conditions-for-2-phase-Flow

My impression is that these saturation "jumps" are most likely happening because the diffuse interface is occupying a significant fraction of the pore volume, making the saturation more sensitive to small shifts in the interface location. This could be an indication that the image is under-resolved for these saturation ranges.  I focus on the saturation range where there are at least 2-4 voxels across a pore throat.

Otherwise, decreasing `morph_delta` is probably the best option.  If you decrease it you should see a smaller change in the volume fraction.

**Comment by maldiH** [comment]
Thanks a lot Prof. McClure for your reply!

I still have a bit of uncertainties regarding the input/domain data for steady-state simulations. 
1. Would that be ok if we define Inletlayers, checker size only for inlet or should it be similarly defined for outlet as well? 
2. if we model steady-state simulation under "image_sequence" protocol using the output domain (id_t..raw) from previous unsteady drainage flow, should we crop 3 voxel layers from inlet and outlet (by offset)? Or it shouldn't create any problems with Sw calculations?

**Comment by JamesEMcClure** [comment]
The checker size is probably not worth using.  The default method is described in this paper (see Fig. 7). 

https://link.springer.com/article/10.1007/s10596-020-10028-9

The checkerboard pattern shouldn't have any advantages compared to this

You probably do want to crop the inlet / outlet out if you use the `image sequence` protocol since it can alter the connectivity of fluids to have a gap. Films will connect across the periodic boundary as long as there is a consistent solid structure.
