### ISSUE TITLE
voxel_length not detected from input

### ISSUE THREAD

**Issue by thomaram** [OPM/LBPM#5]
The set voxel_length from the input.db is not detected in the simulation.

Adding the parameter in the other Domain constructor did not help.

**Comment by JamesEMcClure** [comment]
I had some local changes in my repo that were not yet pushed to OPM. These have now been pushed to morphLBM. This should resolve the issue.  If it does not update me and I will fix it.

**Comment by thomaram** [comment]
Seems to work
