### ISSUE TITLE
Overwrites output

### ISSUE THREAD

**Issue by thomaram** [OPM/LBPM#53]
The simulator starts overwriting the 8 bit visualization steps after the restart. Counter is reset.

**Comment by JamesEMcClure** [comment]
It looks like the code was hitting capillary number rescaling routines that should only be encountered for steady state flow cases. 

This problem should be resolved based on commit 

https://github.com/OPM/LBPM/commit/2ff903f4d560ebd9fd0074d5b68a46d0f5525203
